AWSTemplateFormatVersion: "2010-09-09"
Description: >
  This is a template for servers deployment includes Launch Configuration, Load balancer(LB), 
  Security Groups for LB and WebApp, Auto Scalling Group, a listner with its rule and auto scaling a target group.

Parameters:
  EnvironmentName:
    Description: This is used a prefix for all resources
    Type: String
    Default: deploy-web-app-moemad
  
  WebAppSSHKeyName:
    Description: Enter the Name of the SSH Key Name Created to SSH to WebApp Host from Bastion Host
    Type: String
    Default: UdacityWebAppKey
    
  BastionHostSSHKeyName:
    Description: Enter the name of the SSH Key created to connect with the Bastion Host
    Type: String
    Default: UdacityBastionHostKey
  
  WebAppImageId:
    Description: Enter the AMI Image Id of x64 Ubuntu 18.20 for the region you are deploying in
    Type: String
    # This the us-east-1 region on the date this template created #
    Default: ami-0ee23bfc74a881de5 
  
  BastionHostImageId:
    Description: Enter the AMI Image Id of x64 Amazon linux 2 for your region 
    Type: String
    # This the us-east-1 region on the date this template created #
    Default: ami-0ee23bfc74a881de5

Resources:
  ProfileWithRoleForOurApp:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - UdacityS3ReadOnlyEC2
  
  WebAppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: This Group open ports to allow HTTP to hosts and SSH from Bastion Host
      VpcId: 
        Fn::ImportValue: !Sub ${EnvironmentName}-VPCID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
  
  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: This Group allows traffic HTTP requests to/from load balancers
      VpcId: 
        Fn::ImportValue: !Sub ${EnvironmentName}-VPCID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  
  BastionHostSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: This group allows SSH to and from Bastion Host
      VpcId: 
        Fn::ImportValue: !Sub ${EnvironmentName}-VPCID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  WebAppLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      UserData: 
        Fn::Base64: |
          #!/bin/bash
          apt-get update -y
          apt-get install apache2 -y
          systemctl start apache2.service
          cd /var/www/html
          echo "it works! Udagram, Udacity By Moemad" > index.html
      ImageId: !Ref WebAppImageId
      KeyName: !Ref WebAppSSHKeyName
      SecurityGroups:
        - !Ref WebAppSecurityGroup
      InstanceType: t3.small
      BlockDeviceMappings:
        - DeviceName: /dev/sdk
          Ebs: 
            VolumeSize: 10
Outputs:
