AWSTemplateFormatVersion: "2010-09-09"
Description: >
  This is a template for servers deployment includes Launch Configuration, Load balancer(LB), 
  Security Groups for LB and WebApp, Auto Scalling Group, a listner with its rule and auto scaling a target group.

Parameters:
  EnvironmentName:
    Description: This is used a prefix for all resources
    Type: String
    Default: deploy-web-app-moemad
  
  # WebAppSSHKeyName:
  #   Description: Enter the Name of the SSH Key Name Created to SSH to WebApp Host from Bastion Host
  #   Type: AWS::EC2::KeyPair::KeyName
  #   Default: UdacityWebAppKey
    
  BastionHostSSHKeyName:
    Description: Enter the name of the SSH Key created to connect with the Bastion Host
    Type: AWS::EC2::KeyPair::KeyName
    Default: UdacityBastionHostKey
  
  WebAppImageId:
    Description: Enter the AMI Image Id of x64 Ubuntu Server 18.04 LTS for the region you are deploying in
    Type: AWS::EC2::Image::Id
    # This the us-east-1 region Id on the date this template created #
    Default: ami-0ee23bfc74a881de5 
  
  BastionHostImageId:
    Description: Enter the AMI Image Id of x64 Amazon linux 2 for your region 
    Type: AWS::EC2::Image::Id
    # This the us-east-1 region Id on the date this template created #
    Default: ami-047a51fa27710816e
  
  WebAppInstanceType:
    Description: Enter the instance type for the Web App Servers
    Type: String
    Default: t3.small
  
  BastionHostInstanceType:
    Description: Enter the instance type for the Web App Servers
    Type: String
    Default: t3.micro

Resources:
  # ProfileWithRoleForOurApp:
  #   Type: AWS::IAM::InstanceProfile
  #   Properties:
  #     Roles:
  #       - UdacityS3ReadOnlyEC2
  
  WebAppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: This Group open ports to allow HTTP to hosts and SSH from Bastion Host
      VpcId: 
        Fn::ImportValue: !Sub ${EnvironmentName}-VPCID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
  
  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: This Group allows traffic HTTP requests to/from load balancers
      VpcId: 
        Fn::ImportValue: !Sub ${EnvironmentName}-VPCID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  
  BastionHostSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: This group allows SSH to and from Bastion Host
      VpcId: 
        Fn::ImportValue: !Sub ${EnvironmentName}-VPCID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  WebAppLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      UserData: 
        Fn::Base64: |
          #!/bin/bash
          apt-get update -y
          apt-get install apache2 -y
          systemctl start apache2.service
          cd /var/www/html
          echo "<h1>it works! Udagram, Udacity</h1>" > index.html
      ImageId: !Ref WebAppImageId
      SecurityGroups:
        - !Ref WebAppSecurityGroup
      InstanceType: !Ref WebAppInstanceType
      BlockDeviceMappings:
        - DeviceName: /dev/sdk
          Ebs: 
            VolumeSize: 10
  
  WebAppScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - Fn::ImportValue: !Sub ${EnvironmentName}-PRI-NETS
      LaunchConfigurationName: !Ref WebAppLaunchConfig
      MinSize: 2
      MaxSize: 4
      TargetGroupARNs:
        - !Ref WebAppTargetGroup

  BastionHostInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref BastionHostImageId
      InstanceType: !Ref BastionHostInstanceType
      KeyName: !Ref BastionHostSSHKeyName
      SubnetId: 
        Fn::ImportValue: !Sub ${EnvironmentName}-PUB-SN1
      SecurityGroupIds:
          - !Ref BastionHostSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Bastion Host(Jumpbox)
  
  WebAppLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Subnets:
        - Fn::ImportValue: !Sub ${EnvironmentName}-PUB-SN1
        - Fn::ImportValue: !Sub ${EnvironmentName}-PUB-SN2
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup
  
  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref WebAppTargetGroup
      LoadBalancerArn: !Ref WebAppLoadBalancer
      Port: 80
      Protocol: HTTP
  
  LoadBalancerListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties: 
      Actions:
        - Type: forward
          TargetGroupArn: !Ref WebAppTargetGroup
      Conditions: 
        - Field: path-pattern
          Values: [/]
      ListenerArn: !Ref LoadBalancerListener
      Priority: 1
  
  WebAppTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 8
      HealthyThresholdCount: 2
      Port: 80
      Protocol: HTTP
      UnhealthyThresholdCount: 5
      VpcId: 
        Fn::ImportValue: !Sub ${EnvironmentName}-VPCID

Outputs:
  BastionHostPublicIP:
    Description: The Public IP of the Bastion Host(Jumpbox)
    Value: !Sub http://${BastionHostInstance.PublicIp}
    Export:   
      Name: !Sub ${EnvironmentName}-Bastion-PUB-IP

  BastionHostDNS:
    Description: The Public IP of the Bastion Host(Jumpbox)
    Value: !GetAtt BastionHostInstance.PublicDnsName
    Export:   
      Name: !Sub ${EnvironmentName}-Bastion-PUB-DNS
  
  WebAppDNSURL:
    Description: This is the DNS Name of the Web App Load Balancer
    Value: !Join ["", ["HTTP://",!GetAtt WebAppLoadBalancer.DNSName]]
    Export:
      Name: !Sub ${EnvironmentName}-LB-DNS-NAME
  

  WebAppSecurityGroup:
    Description: This is a reference to the Web Appilication Security Group
    Value: !Ref WebAppSecurityGroup
    Export:
      Name: !Sub ${EnvironmentName}-WEB-APP-SEC-GP
  
  LoadBalancerSecurityGroup:
    Description: This is a reference to the Web Appilication Security Group
    Value: !Ref LoadBalancerSecurityGroup
    Export:
      Name: !Sub ${EnvironmentName}-LB-SEC-GP

  BastionHostSecurityGroup:
    Description: This is a reference to the Web Appilication Security Group
    Value: !Ref BastionHostSecurityGroup
    Export:
      Name: !Sub ${EnvironmentName}-Bastion-SEC-GP
